# Generated by Django 4.1.3 on 2022-12-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('phno', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('radio', models.CharField(max_length=20)),
            ],
        ),
    ]
